Algoritmo "calculo_area_quadrado"
//Calcular a area de um quadrado
// area = lado * lado
Var
// Seção de Declarações das variáveis 
area:real
lado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o valor do lado: ")
 leia (lado)
 //SINTAXE -> REGRA DE ESCRITA DE UMA INSTRUÇÃO
area <- lado * lado
escreva ("A área do quadrado é: ",area)

Fimalgoritmo