Algoritmo "calculo_area_retangulo"
// Lado de um Retangulo
// Area = b * h
Var
// Seção de Declarações das variáveis
area, base, altura:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Escreva o valor da base")
leia (base)
escreva ("Escreva o valor da altura")
leia (altura)

area <- base * altura
escreva ("A área do retângulo é:",area)

Fimalgoritmo